//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BH_ChiTietTraHang
    {
        public int id { get; set; }
        public Nullable<int> idTraHang { get; set; }
        public Nullable<int> idThucDon { get; set; }
        public Nullable<double> soluong { get; set; }
        public Nullable<double> giaGoc { get; set; }
        public Nullable<double> giaNhapLai { get; set; }
        public Nullable<double> lai { get; set; }
    }
}
