//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BH_HoaDonBanHang
    {
        public int id { get; set; }
        public Nullable<int> idLoaiHoaDonBanHang { get; set; }
        public Nullable<int> idKhachHang { get; set; }
        public string idNhanVien { get; set; }
        public Nullable<System.DateTime> thoigian { get; set; }
        public string hinhanh { get; set; }
        public Nullable<double> tongTien { get; set; }
        public Nullable<double> giamgia { get; set; }
        public Nullable<double> thanhtoan { get; set; }
        public Nullable<int> daThanhToan { get; set; }
        public string ghichu { get; set; }
    }
}
