//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KT_ChiTietXuatNguyenLieu
    {
        public int id { get; set; }
        public Nullable<int> idXuatNguyenLieu { get; set; }
        public Nullable<int> idNguyenLieu { get; set; }
        public Nullable<double> dongia { get; set; }
        public Nullable<double> giamgia { get; set; }
        public Nullable<double> soluong { get; set; }
        public Nullable<double> thanhtien { get; set; }
        public string ghichu { get; set; }
    }
}
