//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KT_HangHoa
    {
        public int id { get; set; }
        public string mavach { get; set; }
        public string ma { get; set; }
        public Nullable<int> idNhaSanXuat { get; set; }
        public Nullable<int> idNhomHang { get; set; }
        public Nullable<int> idDonViTinh { get; set; }
        public string ten { get; set; }
        public Nullable<double> giaSi { get; set; }
        public Nullable<double> giaLe { get; set; }
        public Nullable<double> giaVon { get; set; }
        public Nullable<double> hanSuDung { get; set; }
        public Nullable<int> idHanSuDung { get; set; }
        public string mota { get; set; }
        public double soluong { get; set; }
        public Nullable<double> tonToiThieu { get; set; }
        public string hinhanh { get; set; }
        public Nullable<bool> ngungKinhDoanh { get; set; }
        public string ghichu { get; set; }
    }
}
