//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KT_NguyenLieu
    {
        public int id { get; set; }
        public string ma { get; set; }
        public Nullable<int> idNhomNguyenLieu { get; set; }
        public string ten { get; set; }
        public Nullable<int> idDonViTinh { get; set; }
        public Nullable<double> tonToiThieu { get; set; }
        public Nullable<double> hanSuDung { get; set; }
        public Nullable<int> idHanSuDung { get; set; }
        public Nullable<double> soluong { get; set; }
        public string ghichu { get; set; }
    }
}
