//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_HoaDonBanHang
    {
        public int id { get; set; }
        public string idNhanVien { get; set; }
        public string nhanvien { get; set; }
        public Nullable<int> idKhachHang { get; set; }
        public Nullable<int> idDatBan { get; set; }
        public Nullable<int> idBan { get; set; }
        public Nullable<int> soKhach { get; set; }
        public Nullable<System.DateTime> thoigianVao { get; set; }
        public Nullable<System.DateTime> thoigianRa { get; set; }
        public Nullable<double> tongThoiGian { get; set; }
        public bool isHuy { get; set; }
        public Nullable<int> idLyDoHuy { get; set; }
        public Nullable<double> tongTien { get; set; }
        public Nullable<double> giamTien { get; set; }
        public Nullable<double> giamPhanTram { get; set; }
        public Nullable<double> vatTien { get; set; }
        public Nullable<double> vatPhanTram { get; set; }
        public Nullable<bool> isThanhToan { get; set; }
        public Nullable<double> thanhtoan { get; set; }
        public string ghichu { get; set; }
    }
}
