//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_ThemMon
    {
        public int id { get; set; }
        public string idNhanVien { get; set; }
        public Nullable<int> idHoaDonBanHang { get; set; }
        public Nullable<int> idThucDon { get; set; }
        public Nullable<double> soluong { get; set; }
        public Nullable<int> idDonViTinh { get; set; }
        public Nullable<System.DateTime> thoigian { get; set; }
    }
}
