//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_Ban
    {
        public int id { get; set; }
        public Nullable<int> idKhuVuc { get; set; }
        public string ten { get; set; }
        public bool trangthai { get; set; }
        public string ghichu { get; set; }
    }
}
