//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_ThucDon
    {
        public int id { get; set; }
        public string mavach { get; set; }
        public Nullable<int> idNhomThucDon { get; set; }
        public string donvitinh { get; set; }
        public string ten { get; set; }
        public double dongia { get; set; }
        public string huongdan { get; set; }
        public string hinhanh { get; set; }
        public string ghichu { get; set; }
    }
}
