//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Karaoke2017Entities : DbContext
    {
        public Karaoke2017Entities()
            : base("name=Karaoke2017Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRoles> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<DM_Ban> DM_Ban { get; set; }
        public virtual DbSet<DM_DonViTinh> DM_DonViTinh { get; set; }
        public virtual DbSet<DM_DonViThoiGian> DM_DonViThoiGian { get; set; }
        public virtual DbSet<DM_KhachHang> DM_KhachHang { get; set; }
        public virtual DbSet<DM_Kho> DM_Kho { get; set; }
        public virtual DbSet<DM_KhuVuc> DM_KhuVuc { get; set; }
        public virtual DbSet<DM_LoaiHoaDonBanHang> DM_LoaiHoaDonBanHang { get; set; }
        public virtual DbSet<DM_LyDoChi> DM_LyDoChi { get; set; }
        public virtual DbSet<DM_LyDoHuyBan> DM_LyDoHuyBan { get; set; }
        public virtual DbSet<DM_LyDoHuyDatBan> DM_LyDoHuyDatBan { get; set; }
        public virtual DbSet<DM_LyDoNhap> DM_LyDoNhap { get; set; }
        public virtual DbSet<DM_LyDoThu> DM_LyDoThu { get; set; }
        public virtual DbSet<DM_LyDoXuat> DM_LyDoXuat { get; set; }
        public virtual DbSet<DM_MatHang> DM_MatHang { get; set; }
        public virtual DbSet<DM_NhaCungCap> DM_NhaCungCap { get; set; }
        public virtual DbSet<DM_NhanVienPhucVu> DM_NhanVienPhucVu { get; set; }
        public virtual DbSet<DM_NhaSanXuat> DM_NhaSanXuat { get; set; }
        public virtual DbSet<DM_NhomKhachHang> DM_NhomKhachHang { get; set; }
        public virtual DbSet<DM_NhomMatHang> DM_NhomMatHang { get; set; }
        public virtual DbSet<DM_NhomThucDon> DM_NhomThucDon { get; set; }
        public virtual DbSet<DM_ThucDon> DM_ThucDon { get; set; }
        public virtual DbSet<KT_ChiTietNhapHang> KT_ChiTietNhapHang { get; set; }
        public virtual DbSet<KT_ChiTietXuatHang> KT_ChiTietXuatHang { get; set; }
        public virtual DbSet<KT_DinhLuong> KT_DinhLuong { get; set; }
        public virtual DbSet<KT_NhapHang> KT_NhapHang { get; set; }
        public virtual DbSet<KT_NhapNguyenLieu> KT_NhapNguyenLieu { get; set; }
        public virtual DbSet<KT_PhieuChi> KT_PhieuChi { get; set; }
        public virtual DbSet<KT_PhieuThu> KT_PhieuThu { get; set; }
        public virtual DbSet<KT_XuatHang> KT_XuatHang { get; set; }
        public virtual DbSet<KT_XuatNguyenLieu> KT_XuatNguyenLieu { get; set; }
        public virtual DbSet<ORDER_ChiTietChuyenBan> ORDER_ChiTietChuyenBan { get; set; }
        public virtual DbSet<ORDER_ChiTietDatBan> ORDER_ChiTietDatBan { get; set; }
        public virtual DbSet<ORDER_ChiTietHoaDonBanHang> ORDER_ChiTietHoaDonBanHang { get; set; }
        public virtual DbSet<ORDER_ChiTietNhanVienHoaDonBanHang> ORDER_ChiTietNhanVienHoaDonBanHang { get; set; }
        public virtual DbSet<ORDER_ChuyenBan> ORDER_ChuyenBan { get; set; }
        public virtual DbSet<ORDER_DatBan> ORDER_DatBan { get; set; }
        public virtual DbSet<ORDER_GhepBan> ORDER_GhepBan { get; set; }
        public virtual DbSet<ORDER_HoaDonBanHang> ORDER_HoaDonBanHang { get; set; }
    }
}
