//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KT_ChiTietNhapHang
    {
        public int id { get; set; }
        public int idNhapHang { get; set; }
        public int idMatHang { get; set; }
        public double dongia { get; set; }
        public Nullable<double> giamgia { get; set; }
        public double soluong { get; set; }
        public double thanhtien { get; set; }
        public string ghichu { get; set; }
    }
}
