//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KT_NhapHang
    {
        public int id { get; set; }
        public Nullable<int> idLyDoNhap { get; set; }
        public Nullable<int> idNhaCungCap { get; set; }
        public string nguoiNhan { get; set; }
        public Nullable<System.DateTime> thoigian { get; set; }
        public Nullable<double> tongTien { get; set; }
        public Nullable<double> giamGia { get; set; }
        public Nullable<double> thanhtoan { get; set; }
        public string ghichu { get; set; }
    }
}
