//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KT_PhieuChi
    {
        public int id { get; set; }
        public string idNhanVien { get; set; }
        public string nguoiChi { get; set; }
        public Nullable<int> idLyDoChi { get; set; }
        public Nullable<System.DateTime> thoigian { get; set; }
        public Nullable<double> sotien { get; set; }
        public string chungtuKemTheo { get; set; }
        public string nguoiNhan { get; set; }
        public string diachi { get; set; }
        public string sdt { get; set; }
        public string ghichu { get; set; }
    }
}
