//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_DatBan
    {
        public int id { get; set; }
        public string idNhanVien { get; set; }
        public Nullable<int> idKhachHang { get; set; }
        public Nullable<int> idBan { get; set; }
        public string sdt { get; set; }
        public Nullable<int> soKhach { get; set; }
        public Nullable<System.DateTime> thoigianDatBan { get; set; }
        public Nullable<System.DateTime> thoigianHenToi { get; set; }
        public Nullable<System.DateTime> thoigianToi { get; set; }
        public bool isToi { get; set; }
        public bool isHuy { get; set; }
        public Nullable<int> idLyDoHuy { get; set; }
        public Nullable<double> tongTienDuKien { get; set; }
        public Nullable<double> giamDuKienTien { get; set; }
        public Nullable<double> giamDuKienPhanTram { get; set; }
        public Nullable<double> vatDuKienTien { get; set; }
        public Nullable<double> vatDuKienPhanTram { get; set; }
        public Nullable<double> thanhtoanDuKien { get; set; }
        public string ghichu { get; set; }
    }
}
